version: '3.9'

services:
  zookeeper:
    image: zookeeper:3.5
    ports:
      - "2181:2181"
    networks:
      - shared-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://172.17.0.1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: always
    ports:
      - "9092:9092"
    networks:
      - shared-network

  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    networks:
      - shared-network
    depends_on:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    ports:
      - "9001:8080"
    networks:
      - shared-network
    depends_on:
      - kafka

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: -Xms32M -Xmx64M
    ports:
      - "9002:9000"
    networks:
      - shared-network
    depends_on:
      - kafka

volumes:
  mongo-data:


networks:
  shared-network:
    external: true
