version: '3.9'

services:
  zookeeper:
    image: zookeeper:3.5
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - shared-network

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL1://:9092,EXTERNAL2://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL1:PLAINTEXT,EXTERNAL2:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL1://kafka:9092,EXTERNAL2://192.168.100.4:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    networks:
      - shared-network

  kafka_manager:
    restart: unless-stopped
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "zookeeper:2181"
      APPLICATION_SECRET: "random-secret"
    networks:
      - shared-network
    depends_on:
      - kafka

  kafka-ui:
    image: provectuslabs/kafka-ui
    restart: unless-stopped
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    ports:
      - "9001:8080"
    networks:
      - shared-network
    depends_on:
      - kafka

volumes:
  mongo-data:


networks:
  shared-network:
    external: true
